import test from 'node:test'
import assert from 'node:assert/strict'
import { validateOperation,canRecord,canReport,validPrice } from '../src/lib/domain.js'
import { catalog } from '../scripts/initial-tariffs.js'
import { catalog as frontendCatalog } from '../src/lib/catalog.js'
import { summarize,exportCsv,dayKey } from '../src/lib/stats.js'
const base={requestId:'01234567-89101112',sector:'parc',kind:'unit',vehicle:'ab-123-cd',location:'',parcIdentifier:'Lawson 1',operationDate:'2026-10-01',revenue:'1250,50 EUR',serviceIds:['jumelage','navette']}
test('normalise l’identifiant véhicule et conserve les activités indépendantes',()=>{const r=validateOperation(base,catalog);assert.equal(r.vehicle,'AB123CD');assert.equal(r.parcIdentifier,'Lawson 1');assert.equal(r.revenue,'1250,50 EUR');assert.equal(r.services.length,2)})
test('refuse identifiant Lawson/date absents, prestation étrangère, doublons et identifiant invalide',()=>{for(const data of [{...base,parcIdentifier:''},{...base,operationDate:''},{...base,serviceIds:['vo']},{...base,serviceIds:['jumelage','jumelage']},{...base,requestId:'../x'}])assert.throws(()=>validateOperation(data,catalog))})
test('autorise les prestations mixtes et conserve le véhicule',()=>{const r=validateOperation({...base,sector:'atelier',serviceIds:['esthetique','diagnostic']},catalog);assert.equal(r.vehicle,'AB123CD');assert.equal(r.location,'');assert.equal(r.services.find(service=>service.id==='diagnostic').priceCents,null)})
test('permissions : admin et superAdmin, compte désactivé',()=>{assert.equal(canRecord({role:'admin'},'parc'),true);assert.equal(canRecord({role:'superAdmin'},'atelier'),true);assert.equal(canRecord({role:'operator',parc:true},'parc'),false);assert.equal(canReport({role:'admin'}),true);assert.equal(canReport({role:'superAdmin'}),true);assert.equal(canRecord({role:'admin',active:false},'parc'),false)})
test('tarifs en centimes, jamais négatifs ou flottants',()=>{for(const v of [-1,NaN,Infinity,3.28,'328',100000001])assert.equal(validPrice(v),false);for(const v of [null,0,328])assert.equal(validPrice(v),true)})
test('stats exactes, véhicules uniques, forfaits et tarifs inconnus séparés',()=>{const rows=[{vehicle:'AB123CD',operatorId:'a',date:'2026-09-22',kind:'unit',services:[{id:'j',name:'Jumelage',priceCents:328}]},{vehicle:'AB123CD',operatorId:'b',date:'2026-09-22',kind:'unit',services:[{id:'j',name:'Jumelage',priceCents:350}]},{vehicle:'',operatorId:'a',date:'2026-09-22',kind:'daily',services:[{id:'d',name:'Diagnostic',priceCents:null}]}];const s=summarize(rows);assert.equal(s.vehicles,1);assert.equal(s.total,678);assert.equal(s.count,3);assert.equal(s.pending,1);assert.equal(s.operators.length,2);assert.equal(s.services[0].total,678)})
test('export CSV neutralise les formules, échappe les guillemets et utilise le type prestation',()=>{const csv=exportCsv([{date:'2026-09-22',operatorName:'=HYPERLINK("evil")',kind:'unit',services:[{name:'test',kind:'daily',priceCents:328}]}]);assert.ok(csv.includes(`"'=HYPERLINK(""evil"")"`));assert.ok(csv.includes('Forfait journalier'));assert.ok(csv.includes('3,28'))})
test('jour métier en Europe/Paris',()=>assert.equal(dayKey(new Date('2026-09-21T23:00:00Z')),'2026-09-22'))
test('catalogues serveur et interface identiques',()=>assert.deepEqual(catalog.map(({priceCents,...s})=>s),frontendCatalog.map(({initialPriceCents,...s})=>s)))
