<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowRight,ShieldCheck,CarFront,Wrench,Eye,EyeOff } from 'lucide-vue-next'
import { useAuthStore } from '../stores/auth'
import Logo from '../components/Logo.vue'
const router=useRouter(),auth=useAuthStore(),email=ref(''),password=ref(''),error=ref(''),loading=ref(false),showPassword=ref(false)
async function login(){loading.value=true;error.value='';try{const p=await auth.login(email.value.trim(),password.value);await router.push(p.role==='admin'?'/admin':'/home')}catch(e){error.value=e.code?.startsWith('auth/')?'Connexion impossible. Vérifiez vos identifiants et votre connexion.':e.message}finally{loading.value=false}}
</script>
<template><main class="login-page"><section class="login-story"><Logo/><div class="story-content"><div class="eyebrow">PARC & ATELIER · UN SEUL ESPACE</div><h1>L’activité avance.<br>Gardez le fil.</h1><p>Chaque véhicule, chaque prestation, chaque équipe.<br>Tout votre suivi, simplement.</p><div class="story-tags"><span><CarFront :size="18"/> Parc automobile</span><span><Wrench :size="18"/> Atelier</span></div></div><small>Automotive System Repair — Opérations & performance</small></section><section class="login-side"><form class="login-card" @submit.prevent="login"><div class="icon-tile blue"><ShieldCheck :size="25"/></div><div><div class="eyebrow">BIENVENUE SUR ASR</div><h2>Votre espace vous attend.</h2><p>Connectez-vous pour retrouver votre activité.</p></div><label for="email">Adresse e-mail<input id="email" v-model="email" type="email" required autocomplete="username" placeholder="vous@entreprise.fr"/></label><label for="password">Mot de passe<span class="password-field"><input id="password" v-model="password" :type="showPassword?'text':'password'" required autocomplete="current-password" placeholder="Votre mot de passe"/><button type="button" class="password-toggle" :aria-label="showPassword?'Masquer le mot de passe':'Afficher le mot de passe'" @click="showPassword=!showPassword"><EyeOff v-if="showPassword" :size="18"/><Eye v-else :size="18"/></button></span></label><p v-if="error" class="error" role="alert">{{ error }}</p><button class="primary" :disabled="loading">{{ loading?'Connexion en cours…':'Se connecter' }}<ArrowRight :size="18"/></button><p class="login-help">Un problème d’accès ?<br>Contactez votre administrateur.</p></form></section></main></template>
