<script setup>
import{ref,computed,watch}from'vue';import{Check,ArrowRight}from'lucide-vue-next';import{useCatalog}from'../lib/useCatalog';import{call,errorText}from'../lib/api'
const props=defineProps({parc:Boolean,operation:Object}),{services}=useCatalog(),selected=ref([]),hours=ref({}),hours25=ref({}),hours50=ref({}),prorata=ref({}),parcIdentifier=ref('Lawson 1'),operationDate=ref(new Date().toISOString().slice(0,10)),showActivities=ref(false),busy=ref(false),error=ref(''),success=ref('');let requestId=null
const emit=defineEmits(['saved'])
watch(()=>props.operation,row=>{if(!row)return;selected.value=[...(row.serviceIds||[])];hours.value={...row.hours};hours25.value={...row.hours25};hours50.value={...row.hours50};prorata.value={...row.prorata};parcIdentifier.value=row.parcIdentifier||'Lawson 1';operationDate.value=row.date;error.value='';success.value=''}, {immediate:true})
const colors=['#377df4','#e85d75','#2fa37b','#e09b3d','#8b6ee8','#16a6a6','#d66b2f','#607dce','#b04c9b','#579b45','#d04f4f','#3e8bb5','#a98235','#7656a8','#3b9f85','#c45d91','#6e82a8','#a06d4f','#4c9c65','#c24e69'],color=ref(colors[0]);watch(parcIdentifier,v=>color.value=colors[Number(v.replace(/\D/g,''))-1]||colors[0],{immediate:true})
const sector=computed(()=>props.parc?'parc':'atelier'),activities=computed(()=>services.value.filter(s=>s.sector===sector.value&&!['carburant','convoyeur'].includes(s.id)).map(s=>({...s,name:s.id==='jumelage'?`${s.name} · 3,28 €`:s.id==='navette'?`${s.name} · 4,36 €`:s.kind==='daily'?`${s.name} · 177,80 € · Par heure`:s.name}))),selectedServices=computed(()=>activities.value.filter(s=>selected.value.includes(s.id))),hourly=s=>['jumelage','navette'].includes(s.id),name=s=>s.name.split(' · ')[0],rate=s=>s.id==='jumelage'?3.28:s.id==='navette'?4.36:177.8
const calc=(s,map,m=1)=>rate(s)*Number(map.value[s.id]||0)*m,base=s=>hourly(s)?calc(s,hours):prorata.value[s.id]?rate(s)*Number(hours.value[s.id]||7)/7:rate(s),extra25=s=>hourly(s)?calc(s,hours25,1.25):0,extra50=s=>hourly(s)?calc(s,hours50,1.5):0,totalBase=computed(()=>selectedServices.value.reduce((n,s)=>n+base(s),0)),total25=computed(()=>selectedServices.value.reduce((n,s)=>n+extra25(s),0)),total50=computed(()=>selectedServices.value.reduce((n,s)=>n+extra50(s),0)),grand=computed(()=>totalBase.value+total25.value+total50.value),eur=v=>`${v.toFixed(2)} €`
async function submit(){if(busy.value)return;error.value='';success.value='';if(!selected.value.length){error.value='Sélectionnez une activité.';return}busy.value=true;requestId||=crypto.randomUUID();try{await call(props.operation?'updateOperation':'recordOperation',{id:props.operation?.id,requestId,sector:sector.value,vehicle:'',location:'',parcIdentifier:parcIdentifier.value,operationDate:operationDate.value,color:color.value,price:eur(grand.value),hours:hours.value,hours25:hours25.value,hours50:hours50.value,prorata:prorata.value,serviceIds:selected.value});if(props.operation){emit('saved');return}success.value='Saisie enregistrée.';selected.value=[];hours.value={};hours25.value={};hours50.value={};prorata.value={};requestId=null}catch(e){error.value=errorText(e)}finally{busy.value=false}}
</script>
<template><form class="formCard" @submit.prevent="submit"><fieldset :disabled="busy" @input="requestId=null"><label>01 <span>Identifiant et date</span></label><div class="form-row"><select v-model="parcIdentifier"><option v-for="n in 20" :key="n">Lawson {{n}}</option></select><input v-model="operationDate" type="date" required/><span class="lawson-color" :style="{background:color}"></span></div><label>02 <span>Choix des activités</span></label><div class="activity-picker-wrap"><button type="button" class="activity-picker" @click="showActivities=!showActivities">{{selected.length?`${selected.length} activité(s) sélectionnée(s)`:'Sélectionner une ou plusieurs activités'}} <span>⌄</span></button><div v-if="showActivities" class="activity-modal"><div class="activity-dialog"><div class="panel-heading"><h2>Activités</h2><button type="button" class="secondary" @click="showActivities=false">Fermer</button></div><label v-for="s in activities" :key="s.id" class="service" :class="{checked:selected.includes(s.id)}"><input v-model="selected" type="checkbox" :value="s.id"/><span>{{s.name}}</span><Check v-if="selected.includes(s.id)" :size="18"/></label></div></div></div><div v-if="selectedServices.length" class="selected-details"><div v-for="s in selectedServices" :key="s.id" class="selected-detail activity-detail"><strong>{{s.name}}</strong><template v-if="hourly(s)"><label>{{name(s)}} · {{rate(s).toFixed(2).replace('.',',')}} €<input v-model="hours[s.id]" type="number" min="0" step="0.01"/></label><label>{{name(s)}} Heure sup 25 % · {{eur(rate(s)*1.25)}}<input v-model="hours25[s.id]" type="number" min="0" step="0.01"/></label><label>{{name(s)}} Heure sup 50 % · {{eur(rate(s)*1.5)}}<input v-model="hours50[s.id]" type="number" min="0" step="0.01"/></label></template><template v-else><label>Prorata <input v-model="prorata[s.id]" type="checkbox"/></label><input v-if="prorata[s.id]" v-model="hours[s.id]" type="number" min="0.01" step="0.01" placeholder="7 heures / jour"/></template><div class="activity-total">Total {{name(s)}} : <strong>{{eur(base(s)+extra25(s)+extra50(s))}}</strong></div></div></div><div class="totals"><div>Total activités <strong>{{eur(totalBase)}}</strong></div><div>Total heures sup 25 % <strong>{{eur(total25)}}</strong></div><div>Total heures sup 50 % <strong>{{eur(total50)}}</strong></div><div class="grand-total">Grand total <strong>{{eur(grand)}}</strong></div></div></fieldset><p v-if="error" class="error">{{error}}</p><p v-if="success" class="success">{{success}}</p><div class="form-footer"><span>{{selected.length}} activité(s)</span><button class="primary" :disabled="busy||!selected.length">{{busy?'Enregistrement…':operation?'Enregistrer les modifications':'Valider la saisie'}} <ArrowRight :size="18"/></button></div></form></template>
